# Generated by Django 5.1.2 on 2024-10-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('rank', models.CharField(max_length=50, verbose_name='درجه')),
                ('personnel_number', models.CharField(max_length=20, verbose_name='شماره پرسنلی')),
                ('branch', models.CharField(max_length=50, verbose_name='رسته')),
                ('specialty', models.CharField(max_length=100, verbose_name='تخصص')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(max_length=100, verbose_name='محل تولد')),
                ('national_id', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('hire_date', models.DateField(verbose_name='تاریخ استخدام')),
                ('region_entry_date', models.DateField(verbose_name='تاریخ ورود به منطقه')),
                ('instructors_status', models.CharField(max_length=50, verbose_name='وضعیت نظام مدرسین')),
                ('instructors_grade', models.CharField(max_length=50, verbose_name='پایه نظام مدرسین')),
                ('instructors_rank', models.CharField(max_length=50, verbose_name='رتبه نظام مدرسین')),
            ],
        ),
    ]
