# Generated by Django 5.1.2 on 2024-10-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='instructors_status',
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='آیا نظام مدرسین دارد؟'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='instructors_grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='پایه نظام مدرسین'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='instructors_rank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رتبه نظام مدرسین'),
        ),
    ]
